-- Neon-compatible DDL for lorebot schema (docs/AI reference; not applied by the app).
-- See DIFFS.md for differences vs the live Neon project.

CREATE SCHEMA IF NOT EXISTS lorebot;
SET search_path TO lorebot, public;

CREATE TABLE IF NOT EXISTS lorebot.lore (
  lore_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_name varchar(100),
  item_type varchar(30),
  item_is varchar(80),
  submitter varchar(50),
  affects varchar(600),
  apply bigint,
  restricts varchar(200),
  create_date timestamptz,
  class varchar(20),
  mat_class varchar(30),
  material varchar(40),
  item_value varchar(10),
  extra varchar(2000),
  immune varchar(200),
  effects varchar(500),
  weight bigint,
  capacity bigint,
  item_level varchar(80),
  container_size bigint,
  charges bigint,
  speed bigint,
  accuracy bigint,
  power bigint,
  damage varchar(8),
  can_use varchar(200)
);

-- Required for CreateLore / CreateLore_v002 ON CONFLICT ("object_name")
CREATE UNIQUE INDEX IF NOT EXISTS lore_object_name_uidx
  ON lorebot.lore (object_name);

CREATE TABLE IF NOT EXISTS lorebot.person (
  person_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  charname varchar(30) NOT NULL,
  light varchar(100),
  ring1 varchar(100),
  ring2 varchar(100),
  neck1 varchar(100),
  neck2 varchar(100),
  body varchar(100),
  head varchar(100),
  legs varchar(100),
  feet varchar(100),
  arms varchar(100),
  slung varchar(100),
  hands varchar(100),
  shield varchar(100),
  about varchar(100),
  waist varchar(100),
  pouch varchar(100),
  rwrist varchar(100),
  lwrist varchar(100),
  primary_weap varchar(100),
  secondary_weap varchar(100),
  held varchar(100),
  both_hands varchar(100),
  submitter varchar(50),
  create_date timestamptz DEFAULT now(),
  clan_id bigint,
  on_chest varchar(60)
);

-- Required for CreatePerson_v002 ON CONFLICT ("charname")
CREATE UNIQUE INDEX IF NOT EXISTS person_charname_uidx
  ON lorebot.person (charname);
